// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBASRuasrBZ3NUIc2HyW8HJ8G3tkxhrmyA',
    appId: '1:874793508550:android:ea26defee705ed6a4a41c7',
    messagingSenderId: '874793508550',
    projectId: 'jibler-37339',
    databaseURL: 'https://jibler-37339-default-rtdb.firebaseio.com',
    storageBucket: 'jibler-37339.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDrKxsEdFw_GlZGb2vEsn2mRHduX9B4xPY',
    appId: '1:874793508550:ios:482fd78b45752f6c4a41c7',
    messagingSenderId: '874793508550',
    projectId: 'jibler-37339',
    databaseURL: 'https://jibler-37339-default-rtdb.firebaseio.com',
    storageBucket: 'jibler-37339.firebasestorage.app',
    androidClientId: '874793508550-0ita7qrk6t8nej7fr3ti3377j5lnkkah.apps.googleusercontent.com',
    iosBundleId: 'com.qoon.express',
  );
}
